- nodeset:
    name: ansible-collection-ceph-aio-ubuntu-jammy
    nodes:
      - name: aio
        label: ubuntu-jammy
    groups:
      - name: controllers
        nodes:
          - aio
      - name: cephs
        nodes:
          - aio

- nodeset:
    name: ansible-collection-ceph-aio-ubuntu-noble
    nodes:
      - name: aio
        label: ubuntu-noble
    groups:
      - name: controllers
        nodes:
          - aio
      - name: cephs
        nodes:
          - aio

- nodeset:
    name: ansible-collection-ceph-ha-ubuntu-jammy
    nodes:
      - name: mon1
        label: ubuntu-jammy
      - name: mon2
        label: ubuntu-jammy
      - name: mon3
        label: ubuntu-jammy
      - name: osd1
        label: ubuntu-jammy
    groups:
      - name: controllers
        nodes:
          - mon1
          - mon2
          - mon3
      - name: cephs
        nodes:
          - mon1
          - mon2
          - mon3
          - osd1

- nodeset:
    name: ansible-collection-ceph-ha-ubuntu-noble
    nodes:
      - name: mon1
        label: ubuntu-noble
      - name: mon2
        label: ubuntu-noble
      - name: mon3
        label: ubuntu-noble
      - name: osd1
        label: ubuntu-noble
    groups:
      - name: controllers
        nodes:
          - mon1
          - mon2
          - mon3
      - name: cephs
        nodes:
          - mon1
          - mon2
          - mon3
          - osd1

- job:
    name: ansible-collection-ceph-molecule
    parent: molecule
    abstract: true
    vars:
      ceph_fsid: 1dff0e0f-3c44-48da-81cd-4f3c6e8722b2
      ceph_osd_devices:
        - /dev/ceph-{{ inventory_hostname_short }}-osd0/data
        - /dev/ceph-{{ inventory_hostname_short }}-osd1/data
        - /dev/ceph-{{ inventory_hostname_short }}-osd2/data

- job:
    name: ansible-collection-ceph-molecule-aio
    parent: ansible-collection-ceph-molecule
    abstract: true
    vars:
      ceph_bootstrap_single_host_defaults: true

- job:
    name: ansible-collection-ceph-molecule-ha
    parent: ansible-collection-ceph-molecule
    abstract: true

- job:
    name: ansible-collection-ceph-molecule-aio-ubuntu-jammy
    parent: ansible-collection-ceph-molecule-aio
    nodeset: ansible-collection-ceph-aio-ubuntu-jammy

- job:
    name: ansible-collection-ceph-molecule-aio-ubuntu-noble
    parent: ansible-collection-ceph-molecule-aio
    nodeset: ansible-collection-ceph-aio-ubuntu-noble

- job:
    name: ansible-collection-ceph-molecule-ha-ubuntu-jammy
    parent: ansible-collection-ceph-molecule-ha
    nodeset: ansible-collection-ceph-ha-ubuntu-jammy

- job:
    name: ansible-collection-ceph-molecule-ha-ubuntu-noble
    parent: ansible-collection-ceph-molecule-ha
    nodeset: ansible-collection-ceph-ha-ubuntu-noble

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-collection-ceph-molecule-aio-ubuntu-jammy
        - ansible-collection-ceph-molecule-aio-ubuntu-noble
        - ansible-collection-ceph-molecule-ha-ubuntu-jammy
        - ansible-collection-ceph-molecule-ha-ubuntu-noble
        - ansible-test
        - pre-commit
    gate:
      jobs:
        - ansible-collection-ceph-molecule-aio-ubuntu-jammy
        - ansible-collection-ceph-molecule-aio-ubuntu-noble
        - ansible-collection-ceph-molecule-ha-ubuntu-jammy
        - ansible-collection-ceph-molecule-ha-ubuntu-noble
        - ansible-test
        - pre-commit
