# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-collection-ceph-molecule-aio-ubuntu-focal-reef
        - ansible-collection-ceph-molecule-aio-ubuntu-jammy-reef
        - ansible-collection-ceph-molecule-aio-ubuntu-jammy-squid
        - ansible-collection-ceph-molecule-ha-ubuntu-focal-reef
        - ansible-collection-ceph-molecule-ha-ubuntu-jammy-reef
        - ansible-collection-ceph-molecule-ha-ubuntu-jammy-squid
        - ansible-collection-ceph-molecule-ha-upgrade-ubuntu-jammy-reef-to-squid
    gate:
      jobs:
        - ansible-collection-ceph-molecule-aio-ubuntu-focal-reef
        - ansible-collection-ceph-molecule-aio-ubuntu-jammy-reef
        - ansible-collection-ceph-molecule-aio-ubuntu-jammy-squid
        - ansible-collection-ceph-molecule-ha-ubuntu-focal-reef
        - ansible-collection-ceph-molecule-ha-ubuntu-jammy-reef
        - ansible-collection-ceph-molecule-ha-ubuntu-jammy-squid
        - ansible-collection-ceph-molecule-ha-upgrade-ubuntu-jammy-reef-to-squid
