# Copyright (c) 2024 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ceph-molecule-aio-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-aio-2004-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-aio-2004-17:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-aio-2004-16:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-2004-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-2004-17:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-2004-16:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-adopt-upgrade-16-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-adopt-upgrade-16-18:
            dependencies: *molecule_check_dependencies
    gate:
      jobs:
        - ceph-molecule-aio-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-aio-2004-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-aio-2004-17:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-aio-2004-16:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-2004-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-2004-17:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-ha-2004-16:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-adopt-upgrade-16-18:
            dependencies: *molecule_check_dependencies
        - ceph-molecule-adopt-upgrade-16-18:
            dependencies: *molecule_check_dependencies
