# Copyright (c) 2023 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- hosts: all
  tasks:
    - name: Stash the current change
      ansible.builtin.command: git stash
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Checkout pre-cephadm branch
      ansible.builtin.command: git checkout v2.2.0
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Generate random "fsid" using "uuidgen"
      ansible.builtin.command: uuidgen
      register: fsid

    - name: Converge Molecule
      become: true
      ansible.builtin.command: molecule test -s {{ molecule_scenario }}
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        PATH: "{{ ansible_user_dir }}/.venv/bin:{{ ansible_env.PATH }}"
        MOLECULE_DISTRO: "{{ molecule_distro }}"
        MOLECULE_CEPH_VERSION: "{{ ceph_version }}"
        MOLECULE_CEPH_FSID: "{{ fsid.stdout | trim }}"

    - name: Verify Ceph cluster
      become: true
      ansible.builtin.command: molecule verify -s {{ molecule_scenario }}
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        PATH: "{{ ansible_user_dir }}/.venv/bin:{{ ansible_env.PATH }}"
        MOLECULE_DISTRO: "{{ molecule_distro }}"
        MOLECULE_CEPH_VERSION: "{{ ceph_version }}"
        MOLECULE_CEPH_FSID: "{{ fsid.stdout | trim }}"

    - name: Restore the current changes
      ansible.builtin.command: git restore .
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Checkout the current branch
      ansible.builtin.command: git checkout {{ zuul.branch }}
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Stash pop the current changes
      ansible.builtin.command: git stash pop
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Converge Molecule
      become: true
      ansible.builtin.command: molecule test -s {{ molecule_scenario }}
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        PATH: "{{ ansible_user_dir }}/.venv/bin:{{ ansible_env.PATH }}"
        MOLECULE_DISTRO: "{{ molecule_distro }}"
        MOLECULE_CEPH_VERSION: "{{ ceph_version }}"
        MOLECULE_CEPH_FSID: "{{ fsid.stdout | trim }}"

    - name: Verify Ceph cluster
      become: true
      ansible.builtin.command: molecule verify -s {{ molecule_scenario }}
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        PATH: "{{ ansible_user_dir }}/.venv/bin:{{ ansible_env.PATH }}"
        MOLECULE_DISTRO: "{{ molecule_distro }}"
        MOLECULE_CEPH_VERSION: "{{ ceph_version }}"
        MOLECULE_CEPH_FSID: "{{ fsid.stdout | trim }}"
