# Copyright (c) 2023 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- hosts: all
  tasks:
    - name: Install PIP
      ansible.builtin.include_role:
        name: ensure-pip

    - name: Install Molecule
      ansible.builtin.pip:
        chdir: "{{ zuul.project.src_dir }}"
        requirements: requirements.txt

    - name: Uninstall "snapd"
      become: true
      ansible.builtin.apt:
        name: snapd
        state: absent
        purge: true
