# Copyright (c) 2023 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- hosts: all
  roles:
    - ensure-docker
    - ensure-pip
    - ensure-virtualenv

  tasks:
    - name: Install Molecule
      become: true
      ansible.builtin.pip:
        chdir: "{{ zuul.project.src_dir }}"
        requirements: requirements.txt
        virtualenv: "{{ ansible_user_dir }}/.venv"

    - name: Uninstall "snapd"
      become: true
      ansible.builtin.apt:
        name: snapd
        state: absent
        purge: true
